---
title: "05_Biodiversity_additional"
output: html_document
date: "2025-04-29"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      fig.path = "../figures/05_Biodiversity/")
```

## Timing of this script

```{r rmd-start}
# What time did we start running this script? 
start_time <- Sys.time()
```

## Set the seed 
```{r set-seed}
set.seed(20020718)
```

## Load Packages & Colors 

```{r load-packages-colors}
#install packages for stats
#install.packages("rstatix")
#install.packages("ggpubr")

pacman::p_load(tidyverse, devtools, patchwork, iNEXT, phyloseq,
               # packages for stats
               ggpubr, rstatix, install = FALSE)

# Load in colors for plotting 
source("code/colors.R")
```


## Load in Data 

```{r load-data}
load("data/04_PhylogeneticTree/phytree_preprocessed_physeqs.RData")

load("data/05_Biodiversity/iNEXT_data.RData")

metadata_df <- 
  midpoint_rooted_physeq %>%
  sample_data() %>%
  data.frame()
```

```{r manual-rarefaction}

iNEXT_manual_df <- 
  iNEXT_data$iNextEst$size_based %>%
  dplyr::rename(names = Assemblage) %>%
  # fix the samples to merge with metadata 
  #mutate(names = gsub(names, pattern = "[.]", replace = "-"),
  #       names = gsub(names, pattern = "X", replace = "")) %>%
  # join with the metadata
  left_join(., metadata_df, by = "names") %>%
  mutate(station = factor(env_local_scale, levels = c("burn",
                                              "spared",
                                              "rectal",
                                              "perianal"
                                                )))
```


```{r make-obs-df}

obs_div_df <- 
  iNEXT_manual_df %>%
  dplyr::filter(Method == "Observed") 

# Plot boxplots by collection site against diversity
day_0_diversity<-
  obs_div_df %>%
  dplyr::filter(`collection.day.post.admission`=="day-0") %>%
  ggplot(aes(x = env_local_scale, y = qD, fill = env_local_scale, 
             color = env_local_scale)) + 
  facet_wrap(.~Order.q, scales = "free_y") + 
  geom_jitter() + 
  geom_boxplot(alpha = 0.5, outlier.shape = NA) + 
  scale_color_manual(values = colors) + 
  scale_fill_manual(values = colors) + 
  labs(y = "Effective Number of ASVs") + 
  theme_bw() + 
  theme(legend.position = "bottom",
        axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 30,
                                   hjust = 1, 
                                   vjust = 1))
day_0_diversity
```

### Simpson

```{r day-diversity-simpson-burn, fig.height=4, fig.width=4}
# Pull out simpson data 
obs_simps_df <- 
  obs_div_df %>%
  dplyr::filter(Order.q == 2)%>%
  mutate(`collection.day.post.admission` = fct_relevel(`collection.day.post.admission`, c("day-0", "day-3", "day-7","day-14","day-21","day-28")))

# Calculate the ANOVA since the data is normal. :) 
anova_day_simps <- 
  aov(qD ~ `collection.day.post.admission`, data = obs_simps_df)

# Look at it 
anova_day_simps
summary(anova_day_simps)

burn_obs_simp_df<-
  obs_simps_df%>%
  dplyr::filter(env_local_scale=="burn")

# Simpson by collection day
burn_simps_ggboxplot <- 
  ggboxplot(burn_obs_simp_df, x = "collection.day.post.admission", y = "qD", 
          color = "collection.day.post.admission", fill = "collection.day.post.admission", alpha = 0.3,
          outlier.shape = NA) + 
  # Add points
  geom_jitter(aes(color = `collection.day.post.admission`)) + 
  scale_color_manual(values = colors) + 
  scale_fill_manual(values = colors) + 
  labs(y = "# of Dominant ASVs (Simpson)") +
  # Add ANOVA & Tukey
  stat_compare_means(method = "anova", label.y = 35) +  # ANOVA p-value
  geom_pwc(
    aes(group = `collection.day.post.admission`), tip.length = 0, hide.ns = TRUE,
    method = "t_test", label = "p.adj.signif",
    step.increase = 0.08,
    p.adjust.method = "fdr", bracket.nudge.y = -0.08) + 
  theme_bw() + 
  theme(legend.position = "none",
        axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 30,
                                   hjust = 1, 
                                   vjust = 1))
burn_simps_ggboxplot
```

```{r day-diversity-simpson-spared, fig.height=4, fig.width=4}
spared_obs_simp_df<-
  obs_simps_df%>%
  dplyr::filter(env_local_scale=="spared")%>%
  mutate(`collection.day.post.admission` = fct_relevel(`collection.day.post.admission`, c("day-0", "day-3", "day-7","day-14","day-21","day-28")))

# Simpson by day 
spared_simps_ggboxplot <- 
  ggboxplot(spared_obs_simp_df, x = "collection.day.post.admission", y = "qD", 
          color = "collection.day.post.admission", fill = "collection.day.post.admission", alpha = 0.3,
          outlier.shape = NA) + 
  # Add points
  geom_jitter(aes(color = `collection.day.post.admission`)) + 
  scale_color_manual(values = colors) + 
  scale_fill_manual(values = colors) + 
  labs(y = "# of Dominant ASVs (Simpson)") +
  # Add ANOVA & Tukey
  stat_compare_means(method = "anova", label.y = 35) +  # ANOVA p-value
  geom_pwc(
    aes(group = `collection.day.post.admission`), tip.length = 0, hide.ns = TRUE,
    method = "t_test", label = "p.adj.signif",
    step.increase = 0.08,
    p.adjust.method = "fdr", bracket.nudge.y = -0.08) + 
  theme_bw() + 
  theme(legend.position = "none",
        axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 30,
                                   hjust = 1, 
                                   vjust = 1))
spared_simps_ggboxplot
```

###richness

```{r day-diversity-richness-burn, fig.height=4, fig.width=4}
# Pull out richness data 
obs_rich_df <- 
  obs_div_df %>%
  dplyr::filter(Order.q == 0)%>%
  mutate(`collection.day.post.admission` = fct_relevel(`collection.day.post.admission`, c("day-0", "day-3", "day-7","day-14","day-21","day-28")))

# Calculate the ANOVA since the data is normal. :) 
anova_station_rich <- 
  aov(qD ~ `collection.day.post.admission`, data = obs_rich_df)

burn_obs_rich_df<-
  obs_rich_df%>%
  dplyr::filter(env_local_scale=="burn")

# Richness by day
burn_rich_ggboxplot <- 
  ggboxplot(burn_obs_rich_df, x = "collection.day.post.admission", y = "qD", 
          color = "collection.day.post.admission", fill = "collection.day.post.admission", alpha = 0.3,
          outlier.shape = NA) + 
  # Add points
    geom_jitter(aes(color = `collection.day.post.admission`)) + 
  scale_color_manual(values = colors) + 
  scale_fill_manual(values = colors) + 
  labs(y = "# of Total ASVs (Richness)") + 
  # Add ANOVA & Tukey
  stat_compare_means(method = "anova", label.y = min(burn_obs_rich_df$qD)) +  # ANOVA p-value
  geom_pwc(
    aes(group = `collection.day.post.admission`), tip.length = 0, hide.ns = TRUE,
    method = "t_test", label = "p.adj.format",
    p.adjust.method = "fdr", bracket.nudge.y = -0.08) + 
  theme_bw() + 
  theme(legend.position = "none",
        axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 30,
                                   hjust = 1, 
                                   vjust = 1))

burn_rich_ggboxplot
```


```{r day-diversity-richness-spared, fig.height=4, fig.width=4}

spared_obs_rich_df<-
  obs_rich_df%>%
  dplyr::filter(env_local_scale=="spared")%>%
  mutate(`collection.day.post.admission` = fct_relevel(`collection.day.post.admission`, c("day-0", "day-3", "day-7","day-14","day-21","day-28")))

# Richness by day 
spared_rich_ggboxplot <- 
  ggboxplot(spared_obs_rich_df, x = "collection.day.post.admission", y = "qD", 
          color = "collection.day.post.admission", fill = "collection.day.post.admission", alpha = 0.3,
          outlier.shape = NA) + 
  # Add points
    geom_jitter(aes(color = `collection.day.post.admission`)) + 
  scale_color_manual(values = colors) + 
  scale_fill_manual(values = colors) + 
  labs(y = "# of Total ASVs (Richness)") + 
  # Add ANOVA & Tukey
  stat_compare_means(method = "anova", label.y = min(spared_obs_rich_df$qD)) +  # ANOVA p-value
  geom_pwc(
    aes(group = `collection.day.post.admission`), tip.length = 0, hide.ns = TRUE,
    method = "t_test", label = "p.adj.format",
    p.adjust.method = "fdr", bracket.nudge.y = -0.08) + 
  theme_bw() + 
  theme(legend.position = "none",
        axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 30,
                                   hjust = 1, 
                                   vjust = 1))

spared_rich_ggboxplot
```

### shannon
```{r day-diversity-shannon}
obs_shan_df <- 
  obs_div_df %>%
  dplyr::filter(Order.q == 1)%>%
  mutate(`collection.day.post.admission` = fct_relevel(`collection.day.post.admission`, c("day-0", "day-3", "day-7","day-14","day-21","day-28")))

# Calculate the ANOVA since the data is normal. :) 
anova_station_shan <- 
  aov(qD ~ `collection.day.post.admission`, data = obs_shan_df)

burn_obs_shan_df<-
  obs_shan_df%>%
  dplyr::filter(env_local_scale=="burn")

spared_obs_shan_df<-
  obs_shan_df%>%
  dplyr::filter(env_local_scale=="spared")

rectal_obs_shan_df<-
  obs_shan_df%>%
  dplyr::filter(env_local_scale=="rectal")

perianal_obs_shan_df<-
  obs_shan_df%>%
  dplyr::filter(env_local_scale=="perianal")
```

```{r day-diversity-shannon-burn}
burn_shan_ggboxplot <- 
  ggboxplot(burn_obs_shan_df, x = "collection.day.post.admission", y = "qD", 
          color = "collection.day.post.admission", fill = "collection.day.post.admission", alpha = 0.3,
          outlier.shape = NA) + 
  # Add points
    geom_jitter(aes(color = `collection.day.post.admission`)) + 
  scale_color_manual(values = colors) + 
  scale_fill_manual(values = colors) + 
  labs(y = "Eveness of ASVs (Shannon)") + 
  # Add ANOVA & Tukey
  stat_compare_means(method = "anova", label.y = min(burn_obs_shan_df$qD)) +  # ANOVA p-value
  geom_pwc(
    aes(group = `collection.day.post.admission`), tip.length = 0, hide.ns = TRUE,
    method = "t_test", label = "p.adj.format",
    p.adjust.method = "fdr", bracket.nudge.y = -0.08) + 
  theme_bw() + 
  theme(legend.position = "none",
        axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 30,
                                   hjust = 1, 
                                   vjust = 1))
burn_shan_ggboxplot
```

```{r day-diversity-shannon-spared}
spared_shan_ggboxplot <- 
  ggboxplot(spared_obs_shan_df, x = "collection.day.post.admission", y = "qD", 
          color = "collection.day.post.admission", fill = "collection.day.post.admission", alpha = 0.3,
          outlier.shape = NA) + 
  # Add points
    geom_jitter(aes(color = `collection.day.post.admission`)) + 
  scale_color_manual(values = colors) + 
  scale_fill_manual(values = colors) + 
  labs(y = "Eveness of ASVs (Shannon)") + 
  # Add ANOVA & Tukey
  stat_compare_means(method = "anova", label.y = min(spared_obs_shan_df$qD)) +  # ANOVA p-value
  geom_pwc(
    aes(group = `collection.day.post.admission`), tip.length = 0, hide.ns = TRUE,
    method = "t_test", label = "p.adj.format",
    p.adjust.method = "fdr", bracket.nudge.y = -0.08) + 
  theme_bw() + 
  theme(legend.position = "none",
        axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 30,
                                   hjust = 1, 
                                   vjust = 1))
spared_shan_ggboxplot
```

### gut shannon
```{r day-diversity-shannon-rectal}


rectal_shan_ggboxplot <- 
  ggboxplot(rectal_obs_shan_df, x = "collection.day.post.admission", y = "qD", 
          color = "collection.day.post.admission", fill = "collection.day.post.admission", alpha = 0.3,
          outlier.shape = NA) + 
  # Add points
    geom_jitter(aes(color = `collection.day.post.admission`)) + 
  scale_color_manual(values = colors) + 
  scale_fill_manual(values = colors) + 
  labs(y = "Eveness of ASVs (Shannon)") + 
  # Add ANOVA & Tukey
  stat_compare_means(method = "anova", label.y = min(rectal_obs_shan_df$qD)) +  # ANOVA p-value
  geom_pwc(
    aes(group = `collection.day.post.admission`), tip.length = 0, hide.ns = TRUE,
    method = "t_test", label = "p.adj.format",
    p.adjust.method = "fdr", bracket.nudge.y = -0.08) + 
  theme_bw() + 
  theme(legend.position = "none",
        axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 30,
                                   hjust = 1, 
                                   vjust = 1))
rectal_shan_ggboxplot
```

```{r day-diversity-shannon-perianal}
perianal_shan_ggboxplot <- 
  ggboxplot(perianal_obs_shan_df, x = "collection.day.post.admission", y = "qD", 
          color = "collection.day.post.admission", fill = "collection.day.post.admission", alpha = 0.3,
          outlier.shape = NA) + 
  # Add points
    geom_jitter(aes(color = `collection.day.post.admission`)) + 
  scale_color_manual(values = colors) + 
  scale_fill_manual(values = colors) + 
  labs(y = "Eveness of ASVs (Shannon)") + 
  # Add ANOVA & Tukey
  stat_compare_means(method = "anova", label.y = min(perianal_obs_shan_df$qD)) +  # ANOVA p-value
  geom_pwc(
    aes(group = `collection.day.post.admission`), tip.length = 0, hide.ns = TRUE,
    method = "t_test", label = "p.adj.format",
    p.adjust.method = "fdr", bracket.nudge.y = -0.08) + 
  theme_bw() + 
  theme(legend.position = "none",
        axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 30,
                                   hjust = 1, 
                                   vjust = 1))
perianal_shan_ggboxplot
```



## Check Render Time
```{r stop-time}
# Take the time now that we are at the end of the script
end_time <- Sys.time()
end_time 

# Echo the elapsed time
elapsed_time <- round((end_time - start_time), 3)
elapsed_time
```

## Session Information

```{r session-info}
# Ensure reproducibility with package version information
devtools::session_info()
```
